#!/bin/bash
# test
# Config
clips_folder="~/Clips/" # Folder to save clips to

while [ -n "$1" ]; do # while loop starts

	case "$1" in

	-help)
		if [ -z $2 ]; then
		echo "commands -clip, -audio, -shorts"
		fi
		case $2 in 
		clip)
			echo "-clip \$url \$start \$end \$title"
		shift
		;;
		audio)
			echo "-audio url"
		shift
		break
		;;
		esac
		shift

	shift
	;;

	# Clip option
	-clip)

	    if [ -z $url ]; then # Check if the url is already set

	    	url=$2 #Sets the url

			echo $2 $3 $4 $5

        	ffmpeg -ss $3 -to $4 -i "$(youtube-dl -f best --get-url $2)" -c:v copy -c:a copy $5.mp4
			
        else

        	ffmpeg "$(youtube-dl -f best --get-url $url)" -ss $2 -to $3 -i -c:v copy -c:a copy $4.mp4
	fi
        shift
    ;;

	-shorts)

		youtube-dl -f best $2 -o "$clips_folder%(title)s.%(ext)s"

	shift
	;;
	
	-video)
	
	    youtube-dl -f $2 $3
	
	shift
	;;
	
	-audio)

		if [ -z $url ]; then
			
			url=$2

			youtube-dl -f bestaudio[ext=m4a] $2 -o "%(title)s.m4a" --embed-thumbnail --add-metadata
		
		else 
		 	youtube-dl -f bestaudio[ext=m4a] $url -o "%(title)s.m4a" --embed-thumbnail --add-metadata
		fi
		
	shift
	;;

	-title) # Gets the title of the video 
	
	    if [ test -z $url ]; then

	    	url=$2
			youtube-dl --get-title $2

		else

  			youtube-dl --get-title $url

		fi
	shift
	;;
		
	--)
	shift # The double dash makes them parameters

	break
	;;
		
	esac

	shift

done

total=1

for param in "$@"; do

	echo "#$total: $param"

	total=$(($total + 1))

done 